name: ZAP DAST scan
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: First WebApp Scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://demo.testfire.net/'
        
